name: Node CI

on: [push, create]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.9.x, 12.x]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
    - name: Build
      run: |
        npm build
    - name: Test
      run: |
        npm test
      env:
        CI: true
